version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: health_db
    restart: always
    environment:
      POSTGRES_DB: health_monitor
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: health_pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U health_user -d health_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server
      dockerfile: server/Dockerfile
    container_name: health_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://health_user:health_pass123@postgres:5432/health_monitor
      SECRET_KEY: "your-super-secret-jwt-key-change-in-production"
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    container_name: health_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: