"""add user_labels with full composite fk

Revision ID: 1d4711776ec6
Revises: e7d8a8f02832
Create Date: 2025-10-22 14:28:26.705831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4711776ec6'
down_revision: Union[str, None] = 'e7d8a8f02832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.BigInteger(), nullable=True),
    sa.Column('vector_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vector_user_id', sa.Integer(), nullable=True),
    sa.Column('label_type', sa.String(length=50), nullable=False),
    sa.Column('label_value', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vector_id', 'vector_timestamp', 'vector_user_id'], ['a_sensor_vectors.id', 'a_sensor_vectors.timestamp', 'a_sensor_vectors.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_labels')
    # ### end Alembic commands ###
